### ISSUE TITLE
how to use this python file?

### ISSUE THREAD

**Issue by ewwerpm** [JxR-TestMeasure/agilent_663xxx#2]
how to use this python file? Can you get me a demo? thanks, i don't know how to use this python. 这个python该如何用啊？能给个demo吗？谢谢

**Comment by JxR-TestMeasure** [comment]
```
from siglent_sdl1000x import Device as Siglent1000X
from agilent_663xxx import Device as Agilent36621B
import matplotlib.pyplot as plt

ps = Agilent36621B()
load = Siglent1000X()
ps.com.rst()
ps.com.wait()
# Configure load
# Configure pulse
# a: 50mA, 20ms (low level)
# b: 1.5A, 0.2ms (high level)
load.cc.dyn.set_a_and_b(0.05, 3, 0.02, 0.0002)
load.cc.dyn.pulse_mode('CONT')
load.cc.dyn.current_range(5)
load.cc.dyn.voltage_range(36)
load.cc.dyn.set_slew_both(0.5)

# Configure the power supply
ps.ch1.voltage(3.3)
ps.ch1.current('max')
ps.ch1.current_range('max')
# Configure the power supply sampling
ps.log.sample_offset(-10)
ps.log.sample_points(200)
ps.log.integration_time(0.0000156)
# Configure the power supply trigger
ps.log.trig.source('INT')
ps.log.trig.sense('VOLT')
ps.log.trig.voltage_slope('NEG')
ps.log.trig.voltage_level(3.25)

# Commence measurement
ps.ch1.on()
load.cc.dyn.on()
ps.log.start_meas_sample()

# Turn instruments off
load.cc.off()
ps.ch1.off()

# Plot results
plt.plot(ps.log.log_data['seconds'][0:-1], ps.log.log_data['voltage'][0:-1])
#plt.ylim(0, 1.7)
plt.xlim(0, 0.00175)
plt.xlabel(r'time [s]')
plt.ylabel(r'current [A]')
plt.title('Siglent SDL1020X Dynamic CC Pulse Test')
plt.grid()
plt.show()
plt.figure(figsize=(12, 10))
```

**Comment by ewwerpm** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JxR-TestMeasure/agilent_663xxx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月3日(星期六) 下午2:34
收件人:&nbsp;"JxR-TestMeasure/agilent_663xxx"<agilent_663xxx@noreply.github.com&gt;;
抄送:&nbsp;"想你是我的幸福"<1437399109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JxR-TestMeasure/agilent_663xxx] how to use this python file? (#2)





 from siglent_sdl1000x import Device as Siglent1000X from agilent_663xxx import Device as Agilent36621B import matplotlib.pyplot as plt ps = Agilent36621B() load = Siglent1000X() ps.com.rst() ps.com.wait() # Configure load # Configure pulse # a: 50mA, 20ms (low level) # b: 1.5A, 0.2ms (high level) load.cc.dyn.set_a_and_b(0.05, 3, 0.02, 0.0002) load.cc.dyn.pulse_mode('CONT') load.cc.dyn.current_range(5) load.cc.dyn.voltage_range(36) load.cc.dyn.set_slew_both(0.5) # Configure the power supply ps.ch1.voltage(3.3) ps.ch1.current('max') ps.ch1.current_range('max') # Configure the power supply sampling ps.log.sample_offset(-10) ps.log.sample_points(200) ps.log.integration_time(0.0000156) # Configure the power supply trigger ps.log.trig.source('INT') ps.log.trig.sense('VOLT') ps.log.trig.voltage_slope('NEG') ps.log.trig.voltage_level(3.25) # Commence measurement ps.ch1.on() load.cc.dyn.on() ps.log.start_meas_sample() # Turn instruments off load.cc.off() ps.ch1.off() # Plot results plt.plot(ps.log.log_data['seconds'][0:-1], ps.log.log_data['voltage'][0:-1]) #plt.ylim(0, 1.7) plt.xlim(0, 0.00175) plt.xlabel(r'time [s]') plt.ylabel(r'current [A]') plt.title('Siglent SDL1020X Dynamic CC Pulse Test') plt.grid() plt.show() plt.figure(figsize=(12, 10))

**Comment by ewwerpm** [comment]
how to fix this problem?
ValueError: Could not locate a VISA implementation. Install either the IVI binary or pyvisa-py.


E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\Scripts\python.exe E:/JetbrainsCrack/agilent_663xxx-master/663xxx_demo/main.py
Traceback (most recent call last):
&nbsp; File "E:/JetbrainsCrack/agilent_663xxx-master/663xxx_demo/main.py", line 5, in <module&gt;
&nbsp; &nbsp; ps = Agilent36621B()
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\agilent_663xxx.py", line 90, in __init__
&nbsp; &nbsp; self._visa_driver = pyvisa.ResourceManager()
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa\highlevel.py", line 3015, in __new__
&nbsp; &nbsp; visa_library = open_visa_library(visa_library)
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa\highlevel.py", line 2924, in open_visa_library
&nbsp; &nbsp; wrapper = _get_default_wrapper()
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa\highlevel.py", line 2884, in _get_default_wrapper
&nbsp; &nbsp; "Could not locate a VISA implementation. Install either the IVI binary or pyvisa-py."
ValueError: Could not locate a VISA implementation. Install either the IVI binary or pyvisa-py.


Process finished with exit code 1

**Comment by JxR-TestMeasure** [comment]
https://pyvisa.readthedocs.io/en/latest/introduction/getting.html

**Comment by ewwerpm** [comment]
E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\Scripts\python.exe E:/JetbrainsCrack/agilent_663xxx-master/663xxx_demo/main.py
E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\gpib_ctypes\gpib\gpib.py:54: UserWarning: GPIB library not found. Please manually load it using _load_lib(filename). All GPIB functions will raise OSError until the library is manually loaded.
&nbsp; warnings.warn(message)
Traceback (most recent call last):
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa_py\sessions.py", line 195, in get_session_class
&nbsp; &nbsp; return cls._session_classes[(interface_type, resource_class)]
KeyError: (<InterfaceType.gpib: 1&gt;, 'INSTR')


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "E:/JetbrainsCrack/agilent_663xxx-master/663xxx_demo/main.py", line 5, in <module&gt;
&nbsp; &nbsp; ps = Agilent36621B()
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\agilent_663xxx.py", line 91, in __init__
&nbsp; &nbsp; self._bus = self._visa_driver.open_resource(self._address)
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa\highlevel.py", line 3304, in open_resource
&nbsp; &nbsp; res.open(access_mode, open_timeout)
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa\resources\resource.py", line 298, in open
&nbsp; &nbsp; self._resource_name, access_mode, open_timeout
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa\highlevel.py", line 3232, in open_bare_resource
&nbsp; &nbsp; return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa_py\highlevel.py", line 164, in open
&nbsp; &nbsp; parsed.interface_type_const, parsed.resource_class
&nbsp; File "E:\JetbrainsCrack\agilent_663xxx-master\663xxx_demo\my_venv\lib\site-packages\pyvisa_py\sessions.py", line 198, in get_session_class
&nbsp; &nbsp; "No class registered for %s, %s" % (interface_type, resource_class)
ValueError: No class registered for InterfaceType.gpib, INSTR


Process finished with exit code 1

**Comment by JxR-TestMeasure** [comment]
First validate you can connect to your instrument via GPIB and pyVISA **before** even attempting to use the script.  If you can connect, then check:
https://github.com/JxR-TestMeasure/agilent_663xxx/blob/bc5a5d4ba17ddbd86a9c2c250bbaf4d4ba0c6144/agilent_663xxx.py#L88)

Make sure `visa_addr='GPIB0::2::INSTR'` is the correct address.

This is also another way to specify the VISA address of the instrument:
```
from agilent_663xxx import Device as Agilent36621B
ps = Agilent36621B('GPIB0::1::INSTR')   #making sure the passed address is correct for your instrument
```

**Comment by CheerMan1** [comment]
> ```
> from siglent_sdl1000x import Device as Siglent1000X
> from agilent_663xxx import Device as Agilent36621B
> import matplotlib.pyplot as plt
> 
> ps = Agilent36621B()
> load = Siglent1000X()
> ps.com.rst()
> ps.com.wait()
> # Configure load
> # Configure pulse
> # a: 50mA, 20ms (low level)
> # b: 1.5A, 0.2ms (high level)
> load.cc.dyn.set_a_and_b(0.05, 3, 0.02, 0.0002)
> load.cc.dyn.pulse_mode('CONT')
> load.cc.dyn.current_range(5)
> load.cc.dyn.voltage_range(36)
> load.cc.dyn.set_slew_both(0.5)
> 
> # Configure the power supply
> ps.ch1.voltage(3.3)
> ps.ch1.current('max')
> ps.ch1.current_range('max')
> # Configure the power supply sampling
> ps.log.sample_offset(-10)
> ps.log.sample_points(200)
> ps.log.integration_time(0.0000156)
> # Configure the power supply trigger
> ps.log.trig.source('INT')
> ps.log.trig.sense('VOLT')
> ps.log.trig.voltage_slope('NEG')
> ps.log.trig.voltage_level(3.25)
> 
> # Commence measurement
> ps.ch1.on()
> load.cc.dyn.on()
> ps.log.start_meas_sample()
> 
> # Turn instruments off
> load.cc.off()
> ps.ch1.off()
> 
> # Plot results
> plt.plot(ps.log.log_data['seconds'][0:-1], ps.log.log_data['voltage'][0:-1])
> #plt.ylim(0, 1.7)
> plt.xlim(0, 0.00175)
> plt.xlabel(r'time [s]')
> plt.ylabel(r'current [A]')
> plt.title('Siglent SDL1020X Dynamic CC Pulse Test')
> plt.grid()
> plt.show()
> plt.figure(figsize=(12, 10))
> ```


Traceback (most recent call last):
  File "C:\Users\86176\Desktop\project\pyTools\_pyvisa\main.py", line 2, in <module>
    from siglent_sdl1000x import Device as Siglent1000X
ModuleNotFoundError: No module named 'siglent_sdl1000x'

In fact, most people just need to set/get the voltage value, set/get the current value, and enable the output. Can you provide examples of just these features

Thank you. You're the most respectable friend in the world
